### ISSUE TITLE
hibernate class missing

### ISSUE THREAD

**Issue by coolcut69** [spring-guides/gs-crud-with-vaadin#12]
when trying to run the project from the initial folder I'm getting an error about a hibernate class not found

Caused by: java.lang.ClassNotFoundException: org.hibernate.HibernateException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_162]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[gs-crud-with-vaadin-0.1.0.jar:0.1.0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_162]
	... 67 common frames omitted

**Comment by snicoll** [comment]
@coolcut69 I can't reproduce the problem, perhaps a jar file got corrupted? Check you maven/Gradle cache please.

**Comment by snicoll** [comment]
Closing due to lack of feedback.
